### ISSUE TITLE
com.leavay.model.exception.McValidationException: "中文名称" attr.validate.error. 

### ISSUE THREAD

**Issue by weijianhuaaccp** [bugmeng/idfissues#4]
1.问题现象：com.leavay.model.exception.McValidationException: "中文名称" attr.validate.error. 
2.跟踪日志：无
3.堆栈日志：*************DISTRIBUTE_TJDS_DWADMIN.H_F_PAYINPSM不存在,开始创建************
Exception : Error occurs at 'autoBuild_tyst' (Line:854). 
Fail Cause: Error occurs at 'Glocal Function : createDistributePDR( ... )' (Line:294). 
Fail Cause: service.createPSM(psm): null
org.mvel2.ASTExecuteException: Error occurs at 'autoBuild_tyst' (Line:854). 
错误原因 :  Error occurs at 'Glocal Function : createDistributePDR( ... )' (Line:294). 
错误原因 :  service.createPSM(psm): null
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:187)
	at org.mvel2.MVEL.executeDebugger(MVEL.java:1207)
	at org.mvel2.LJava$MVELExe.executeDebugger(LJava.java:136)
	at sun.reflect.GeneratedMethodAccessor317.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mvel2.LJava.executeDebugger(LJava.java:182)
	at org.mvel2.rmtLaunch.RemoteLaunchHost.realExecuteRemoteLauncher(RemoteLaunchHost.java:202)
	at org.mvel2.rmtLaunch.RemoteLaunchHost._doExecuteRmtLaunch(RemoteLaunchHost.java:125)
	at sun.reflect.GeneratedMethodAccessor316.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.leavay.common.util.ToolUtilities.callFunction(ToolUtilities.java:3422)
	at com.leavay.common.util.ToolUtilities$AnsyncCallThread.run(ToolUtilities.java:3300)
由此错误引起 :  [Error: Error occurs at 'Glocal Function : createDistributePDR( ... )' (Line:294). 
错误原因 :  service.createPSM(psm): null]
[Line: 854]
[Near : {... autoBuild_tyst() ...}
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:458)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:204)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:215)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	... 13 more
由此错误引起 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : createDistributePDR( ... )' (Line:294). 
错误原因 :  service.createPSM(psm): null
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:187)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:88)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.ForEachNode.getReducedValueAccelerated(ForEachNode.java:166)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.Function.call(Function.java:181)
	at com.leavay.dfc.mgr.env.FunctionWrapper.call(FunctionWrapper.java:191)
	at org.mvel2.optimizers.impl.refl.nodes.FunctionAccessor.getValue(FunctionAccessor.java:49)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:172)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.TypedVarNode.getReducedValueAccelerated(TypedVarNode.java:85)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:88)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.ForNode.getReducedValueAccelerated(ForNode.java:70)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.Function.call(Function.java:181)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getMethod(ReflectiveAccessorOptimizer.java:932)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:385)
	... 16 more
由此错误引起 :  [Error: service.createPSM(psm): null]
[Line: 294]
[Near : {... service.createPSM(psm) ...}
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:443)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:204)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:215)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	... 48 more
由此错误引起 :  java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getMethod(ReflectiveAccessorOptimizer.java:1013)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:385)
	... 51 more
由此错误引起 :  com.leavay.model.exception.McValidationException: "中文名称" attr.validate.error. 
	at com.leavay.model.inf.AbsManagedData.validation(AbsManagedData.java:886)
	at com.leavay.model.inf.AbsManagedData.validation(AbsManagedData.java:850)
	at modeldef.com.leavay.dfc.mda.PIMBase.verifyDBEntity(PIMBase.java:1826)
	at modeldef.com.leavay.dfc.mda.PIMBase.verifyEntity(PIMBase.java:1806)
	at modeldef.com.leavay.dfc.mda.PIMBase.verifyEntity(PIMBase.java:1781)
	at com.leavay.dfc.mgr.mdaMgr.createPSM(mdaMgr.java:1687)
	at com.leavay.dfc.mgr.mdaMgr.createPSM(mdaMgr.java:1664)
	at com.leavay.dfc.mgr.dfcImpl.createPSM(dfcImpl.java:841)
	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.t
4.尝试过的解决方式：

**Comment by bugmeng** [comment]
DISTRIBUTE_TJDS_DWADMIN.H_F_PAYINPSM不存在,开始创建 命名规则都不对，这个schema最少要4三个_现在怎么就两个？
