### ISSUE TITLE
抽取R_SINGLECARBOAT全量时报这个错Too many bad records!

### ISSUE THREAD

**Issue by weijianhuaaccp** [bugmeng/idfissues#6]
1.问题现象：抽取R_SINGLECARBOAT全量时报这个错Too many bad records!
2.跟踪日志：
运行在代理(Agent3)上 : 133.12.57.153 (dsjpt-sjgc1) : 1077
[===== "从PDR中加载作业 : runJob" =====]  已完成(2018-07-18 10:59:59  --  2018-07-18 11:00:05,  5704ms)
[2018-07-18 10:59:59,977] 解析作业内容
[2018-07-18 10:59:59,980] 完成作业加载，准备执行
[2018-07-18 10:59:59,980] 开始加载环境变量
[2018-07-18 11:00:00,0] 完成环境变量加载
[===== "ODS_FFK_CCS_TJDS.R_SINGLECARBOAT<runJob>" =====]  异常(2018-07-18 11:00:00  --  2018-07-18 11:00:05,  5681ms)
[===== "加载数据动作(lddata)" =====]  异常(2018-07-18 11:00:00  --  2018-07-18 11:00:05,  5679ms)
[2018-07-18 11:00:00,66] 准备执行sql:drop table ODS_FFK_CCS_TJDS.R_SINGLECARBOAT
[2018-07-18 11:00:00,76] ds____[Class=com.leavay.dfc.physical.DBDatasource;id=-1|[ID= -1,driverClass= com.gbase.jdbc.Driver,minConns= 1,url= jdbc:gbase://192.168.157.149:5258/ODS_FFK_CCS_TJDS?failoverEnabl...,maxConns= 2,password= voo^y6Ae,CLASS= com.leavay.dfc.physical.DBDatasource,userName= bbUser,]]<TableName=null>
[2018-07-18 11:00:00,76] rt_driver____com.gbase.jdbc.Driver
[2018-07-18 11:00:00,77] url:jdbc:gbase://192.168.157.149:5258/ODS_FFK_CCS_TJDS?failoverEnable=true&hostList=192.168.157.149,192.168.157.150,192.168.157.151&gclusterId=gcl1
[2018-07-18 11:00:00,414] ODS_FFK_CCS_TJDS.R_SINGLECARBOAT______TYST
[2018-07-18 11:00:00,431] TDG3
[2018-07-18 11:00:00,965] 当前表结构为复制表,参考guid为：ODS_FFK_CCS_TJDS.R_SINGLECARBOAT
[2018-07-18 11:00:00,965] ODS_FFK_CCS_TJDS.R_SINGLECARBOAT执行的创建代码表的sql为:create table if not exists ODS_FFK_CCS_TJDS.R_SINGLECARBOAT 
(RSCB_ID VARCHAR(60), 
RCB_TYPE VARCHAR(30), 
RTP_ID VARCHAR(60), 
TJTAX_DATE DATETIME, 
RSCB_NUM DECIMAL(14,3), 
RSCB_LNUM DECIMAL(14,3), 
RSCB_BIT DECIMAL(9,5), 
RSCB_LEVYNUM DECIMAL(13,2), 
RSCB_IFFREE CHAR(3), 
RSCB_HAVE DECIMAL(13,2), 
RSCB_SZLS VARCHAR(38), 
RSCB_TYPE VARCHAR(30), 
PZLX VARCHAR(6), 
DJRQ DATETIME, 
ZJRQ DATETIME, 
PL DECIMAL(18,2), 
ZKRC VARCHAR(18), 
DZ VARCHAR(6), 
CLLX VARCHAR(12), 
RTP_TYPE VARCHAR(38), 
MCR_ID VARCHAR(3), 
YCPZH VARCHAR(60), 
BTOF_ID VARCHAR(18), 
RSCB_DATE DATETIME, 
RSCB_SING VARCHAR(38), 
FDJH VARCHAR(90), 
BZ VARCHAR(600), 
CZXM VARCHAR(1200), 
CZDZ VARCHAR(360), 
XGYY VARCHAR(600), 
RS_STRUCTCODE VARCHAR(90), 
CARSOURCE VARCHAR(38), 
PPXH VARCHAR(450), 
DJXH VARCHAR(20), 
NSRSBH VARCHAR(20), 
SSSWJGDM VARCHAR(11), 
JDXZDM VARCHAR(9), 
SL DECIMAL(16,6), 
SYXZ VARCHAR(300), 
JDCRLNYZLDM VARCHAR(1), 
JLDWDM VARCHAR(4), 
FLAG VARCHAR(4), 
J3EXISTFLAG VARCHAR(1), 
CHANGESTATUS VARCHAR(20), 
DZNEW VARCHAR(6), 
TEL VARCHAR(60)) ENGINE=EXPRESS REPLICATED DEFAULT CHARSET=utf8 TABLESPACE='sys_tablespace'
[2018-07-18 11:00:00,965] 准备执行sql:create table if not exists ODS_FFK_CCS_TJDS.R_SINGLECARBOAT 
(RSCB_ID VARCHAR(60), 
RCB_TYPE VARCHAR(30), 
RTP_ID VARCHAR(60), 
TJTAX_DATE DATETIME, 
RSCB_NUM DECIMAL(14,3), 
RSCB_LNUM DECIMAL(14,3), 
RSCB_BIT DECIMAL(9,5), 
RSCB_LEVYNUM DECIMAL(13,2), 
RSCB_IFFREE CHAR(3), 
RSCB_HAVE DECIMAL(13,2), 
RSCB_SZLS VARCHAR(38), 
RSCB_TYPE VARCHAR(30), 
PZLX VARCHAR(6), 
DJRQ DATETIME, 
ZJRQ DATETIME, 
PL DECIMAL(18,2), 
ZKRC VARCHAR(18), 
DZ VARCHAR(6), 
CLLX VARCHAR(12), 
RTP_TYPE VARCHAR(38), 
MCR_ID VARCHAR(3), 
YCPZH VARCHAR(60), 
BTOF_ID VARCHAR(18), 
RSCB_DATE DATETIME, 
RSCB_SING VARCHAR(38), 
FDJH VARCHAR(90), 
BZ VARCHAR(600), 
CZXM VARCHAR(1200), 
CZDZ VARCHAR(360), 
XGYY VARCHAR(600), 
RS_STRUCTCODE VARCHAR(90), 
CARSOURCE VARCHAR(38), 
PPXH VARCHAR(450), 
DJXH VARCHAR(20), 
NSRSBH VARCHAR(20), 
SSSWJGDM VARCHAR(11), 
JDXZDM VARCHAR(9), 
SL DECIMAL(16,6), 
SYXZ VARCHAR(300), 
JDCRLNYZLDM VARCHAR(1), 
JLDWDM VARCHAR(4), 
FLAG VARCHAR(4), 
J3EXISTFLAG VARCHAR(1), 
CHANGESTATUS VARCHAR(20), 
DZNEW VARCHAR(6), 
TEL VARCHAR(60)) ENGINE=EXPRESS REPLICATED DEFAULT CHARSET=utf8 TABLESPACE='sys_tablespace'
[2018-07-18 11:00:00,977] ds____[Class=com.leavay.dfc.physical.DBDatasource;id=-1|[ID= -1,driverClass= com.gbase.jdbc.Driver,minConns= 1,url= jdbc:gbase://192.168.157.149:5258/ODS_FFK_CCS_TJDS?failoverEnabl...,maxConns= 2,password= voo^y6Ae,CLASS= com.leavay.dfc.physical.DBDatasource,userName= bbUser,]]<TableName=null>
[2018-07-18 11:00:00,977] rt_driver____com.gbase.jdbc.Driver
[2018-07-18 11:00:00,977] url:jdbc:gbase://192.168.157.149:5258/ODS_FFK_CCS_TJDS?failoverEnable=true&hostList=192.168.157.149,192.168.157.150,192.168.157.151&gclusterId=gcl1
[2018-07-18 11:00:01,179] ODS_FFK_CCS_TJDS.R_SINGLECARBOAT______TYST
[2018-07-18 11:00:01,464] CCS
[2018-07-18 11:00:01,483] TDG3
[2018-07-18 11:00:01,838] TDG3
[2018-07-18 11:00:02,190] TDG3
[2018-07-18 11:00:02,523] TDG3
[2018-07-18 11:00:02,896] 当前返回字段内容为：RSCB_ID,RCB_TYPE,RTP_ID,TJTAX_DATE,RSCB_NUM,RSCB_LNUM,RSCB_BIT,RSCB_LEVYNUM,RSCB_IFFREE,RSCB_HAVE,RSCB_SZLS,RSCB_TYPE,PZLX,DJRQ,ZJRQ,PL,ZKRC,DZ,CLLX,RTP_TYPE,MCR_ID,YCPZH,BTOF_ID,RSCB_DATE,RSCB_SING,FDJH,BZ,CZXM,CZDZ,XGYY,RS_STRUCTCODE,CARSOURCE,PPXH,DJXH,NSRSBH,SSSWJGDM,JDXZDM,SL,SYXZ,JDCRLNYZLDM,JLDWDM,FLAG,J3EXISTFLAG,CHANGESTATUS,DZNEW,TEL,CARFROM
[2018-07-18 11:00:02,896] 提醒：代码表一直处理全量数据,保存到全量地址,当前准备处理的SQL为：LOAD DATA INFILE 'sftp://idf:Ies9sai|@192.168.157.153//export/idf/data/all/FFK/CCS/TJDS/R_SINGLECARBOAT.txt' INTO TABLE ODS_FFK_CCS_TJDS.R_SINGLECARBOAT DATA_FORMAT 3  FIELDS TERMINATED BY '\x05\x1E'  TABLE_FIELDS 'RSCB_ID,RCB_TYPE,RTP_ID,TJTAX_DATE,RSCB_NUM,RSCB_LNUM,RSCB_BIT,RSCB_LEVYNUM,RSCB_IFFREE,RSCB_HAVE,RSCB_SZLS,RSCB_TYPE,PZLX,DJRQ,ZJRQ,PL,ZKRC,DZ,CLLX,RTP_TYPE,MCR_ID,YCPZH,BTOF_ID,RSCB_DATE,RSCB_SING,FDJH,BZ,CZXM,CZDZ,XGYY,RS_STRUCTCODE,CARSOURCE,PPXH,DJXH,NSRSBH,SSSWJGDM,JDXZDM,SL,SYXZ,JDCRLNYZLDM,JLDWDM,FLAG,J3EXISTFLAG,CHANGESTATUS,DZNEW,TEL,CARFROM' LINES TERMINATED BY '\x06\x1F' MAX_BAD_RECORDS 0  DATETIME FORMAT '%Y-%m-%d %H:%i:%s.%f' TIMESTAMP FORMAT '%Y-%m-%d %H:%i:%s.%f' PARALLEL 4
[2018-07-18 11:00:02,896] ds____[Class=com.leavay.dfc.physical.DBDatasource;id=-1|[ID= -1,driverClass= com.gbase.jdbc.Driver,minConns= 1,url= jdbc:gbase://192.168.157.149:5258/ODS_FFK_CCS_TJDS?failoverEnabl...,maxConns= 2,password= voo^y6Ae,CLASS= com.leavay.dfc.physical.DBDatasource,userName= bbUser,]]<TableName=null>
[2018-07-18 11:00:02,896] rt_driver____com.gbase.jdbc.Driver
[2018-07-18 11:00:02,897] url:jdbc:gbase://192.168.157.149:5258/ODS_FFK_CCS_TJDS?failoverEnable=true&hostList=192.168.157.149,192.168.157.150,192.168.157.151&gclusterId=gcl1
[2018-07-18 11:00:02,908] 当前检查增量准备区表是否存在的sql为:select count(1) c from information_schema.tables where table_schema = 'ODS_FFK_CCS_TJDS' and table_name = 'R_SINGLECARBOAT'
[2018-07-18 11:00:02,909] ****************此表已存在,清除表中旧数据*当前变量rowcount：1******************
[2018-07-18 11:00:02,912] 执行清除数据的sql为：truncate table ODS_FFK_CCS_TJDS.R_SINGLECARBOAT
[2018-07-18 11:00:03,22] 执行加载sql为LOAD DATA INFILE 'sftp://idf:Ies9sai|@192.168.157.153//export/idf/data/all/FFK/CCS/TJDS/R_SINGLECARBOAT.txt' INTO TABLE ODS_FFK_CCS_TJDS.R_SINGLECARBOAT DATA_FORMAT 3  FIELDS TERMINATED BY '\x05\x1E'  TABLE_FIELDS 'RSCB_ID,RCB_TYPE,RTP_ID,TJTAX_DATE,RSCB_NUM,RSCB_LNUM,RSCB_BIT,RSCB_LEVYNUM,RSCB_IFFREE,RSCB_HAVE,RSCB_SZLS,RSCB_TYPE,PZLX,DJRQ,ZJRQ,PL,ZKRC,DZ,CLLX,RTP_TYPE,MCR_ID,YCPZH,BTOF_ID,RSCB_DATE,RSCB_SING,FDJH,BZ,CZXM,CZDZ,XGYY,RS_STRUCTCODE,CARSOURCE,PPXH,DJXH,NSRSBH,SSSWJGDM,JDXZDM,SL,SYXZ,JDCRLNYZLDM,JLDWDM,FLAG,J3EXISTFLAG,CHANGESTATUS,DZNEW,TEL,CARFROM' LINES TERMINATED BY '\x06\x1F' MAX_BAD_RECORDS 0  DATETIME FORMAT '%Y-%m-%d %H:%i:%s.%f' TIMESTAMP FORMAT '%Y-%m-%d %H:%i:%s.%f' PARALLEL 4
3.堆栈日志：
1 . 在执行“加载数据动作(lddata)”节点时发生错误，错误内容：Error occurs at 'TYST_DM_MODEL..加载数据动作' (Line:6). 
    Fail Cause: Error occurs at 'Glocal Function : runTystDMModel( ... )' (Line:32). 
    Fail Cause: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
    Fail Cause: org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
    Fail Cause: st.executeUpdate(sql_load): null
2 . Error occurs at 'TYST_DM_MODEL..加载数据动作' (Line:6). 
    Fail Cause: Error occurs at 'Glocal Function : runTystDMModel( ... )' (Line:32). 
    Fail Cause: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
    Fail Cause: org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
    Fail Cause: st.executeUpdate(sql_load): null
3 . Error occurs at 'Glocal Function : runTystDMModel( ... )' (Line:32). 
    Fail Cause: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
    Fail Cause: org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
    Fail Cause: st.executeUpdate(sql_load): null
4 . Error occurs at 'Glocal Function : runTystDMModel( ... )' (Line:32). 
    Fail Cause: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
    Fail Cause: org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
    Fail Cause: st.executeUpdate(sql_load): null
5 . Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
    Fail Cause: org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
    Fail Cause: st.executeUpdate(sql_load): null
6 . Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
    Fail Cause: org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
    Fail Cause: st.executeUpdate(sql_load): null
7 . org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
    Fail Cause: st.executeUpdate(sql_load): null
8 . Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
    Fail Cause: st.executeUpdate(sql_load): null
9 . st.executeUpdate(sql_load): null
10 . InvocationTargetException
11 . (GBA-01EX-700) Gbase general error: Task 681372 failed, [192.168.157.149:5050](GBA-02AD-0005)Failed to query in gnode:
    DETAIL: (GBA-01-600) Gbase internal error: Task 681372, Too many bad records!
    SQL: LOAD /*+ TID('104925321') */ DATA INFILE 'sftp://idf:Ies9sai|@192.168.157.153//export/idf/data/all/FFK/CCS/TJDS/R_SINGLECARBOAT.txt#offset=0&length=343910733&firstblock&ffsize=1375642931' INTO TABLE `ods_ffk_ccs_tjds`.`r_singlecarboat` DATA_FORMAT 3 FIELDS TERMINATED BY '' TABLE_FIELDS 'RSCB_ID,RCB_TYPE,RT

运行“加载数据动作(lddata)”失败。
com.leavay.dfc.mgr.dataFlow.ResultStatus.LastStepException: 运行“加载数据动作(lddata)”失败。
	at com.leavay.dfc.mgr.dataFlow.FlowCtrlNode.throwErrorBrach(FlowCtrlNode.java:319)
	at com.leavay.dfc.mgr.dataFlow.FlowCtrlNode.run(FlowCtrlNode.java:418)
	at com.leavay.dfc.mgr.dataFlow.FlowCtrlNode$ThreadParallel.run(FlowCtrlNode.java:571)
	at com.leavay.dfc.mgr.dataFlow.FlowCtrlNode.runParallelNode(FlowCtrlNode.java:630)
	at com.leavay.dfc.mgr.dataFlow.FlowCtrlNode.transitToNextNode(FlowCtrlNode.java:466)
	at com.leavay.dfc.mgr.dataFlow.FlowCtrlNode.run(FlowCtrlNode.java:430)
	at com.leavay.dfc.mgr.etl.TJob_Flow.excute(TJob_Flow.java:256)
	at com.leavay.dfc.mgr.etl.TJob_Flow.excute(TJob_Flow.java:245)
	at com.leavay.dfc.mgr.dataFlow.DFlowEngine.realExecuteOneT(DFlowEngine.java:277)
	at com.leavay.dfc.mgr.dataFlow.DFlowEngine.executeOneETL(DFlowEngine.java:207)
	at com.leavay.dfc.mgr.dataFlow.DCoreHandler.realExecute(DCoreHandler.java:12)
	at com.leavay.dfc.mgr.dataFlow.AsyncJobWorker.run(AsyncJobWorker.java:58)
	at com.leavay.dfc.mgr.dataFlow.AsyncPsmJobWorker.run(AsyncPsmJobWorker.java:87)
	at com.leavay.client.util.CmnEvent.CmnThreadPool.realRunRunnable(CmnThreadPool.java:1019)
	at com.leavay.client.util.CmnEvent.CmnThreadPool$ThreadWorker.run(CmnThreadPool.java:843)
由此错误引起 :  com.leavay.dfc.mgr.etl.Exception.TRunningException: 在执行“加载数据动作(lddata)”节点时发生错误，错误内容：Error occurs at 'TYST_DM_MODEL..加载数据动作' (Line:6). 
错误原因 :  Error occurs at 'Glocal Function : runTystDMModel( ... )' (Line:32). 
错误原因 :  Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
错误原因 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
错误原因 :  st.executeUpdate(sql_load): null
	at com.leavay.dfc.mgr.etl.AbstractJob.runOneComponent(AbstractJob.java:64)
	at com.leavay.dfc.mgr.etl.FlowHandlerForT.handleEven(FlowHandlerForT.java:79)
	at com.leavay.dfc.mgr.dataFlow.FlowCtrlNode.runOneHandler(FlowCtrlNode.java:526)
	at com.leavay.dfc.mgr.dataFlow.FlowCtrlNode.runAllHandler(FlowCtrlNode.java:497)
	at com.leavay.dfc.mgr.dataFlow.FlowCtrlNode.run(FlowCtrlNode.java:412)
	... 13 more
由此错误引起 :  org.mvel2.ASTExecuteException: Error occurs at 'TYST_DM_MODEL..加载数据动作' (Line:6). 
错误原因 :  Error occurs at 'Glocal Function : runTystDMModel( ... )' (Line:32). 
错误原因 :  Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
错误原因 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
错误原因 :  st.executeUpdate(sql_load): null
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:187)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.MVEL.executeExpression(MVEL.java:1055)
	at org.mvel2.LJava.executeExpression(LJava.java:89)
	at com.leavay.dfc.mgr.etl.LvLJava.executeExpression(LvLJava.java:36)
	at com.leavay.dfc.mgr.etl.component.T_LJavaScript.realExecuteScript(T_LJavaScript.java:169)
	at com.leavay.dfc.mgr.etl.component.T_LJavaScript.excute(T_LJavaScript.java:133)
	at com.leavay.dfc.mgr.dataFlow.DFlowEngine.realExecuteOneT(DFlowEngine.java:277)
	at com.leavay.dfc.mgr.etl.AbstractJob.runOneComponent(AbstractJob.java:44)
	... 17 more
由此错误引起 :  [Error: Error occurs at 'Glocal Function : runTystDMModel( ... )' (Line:32). 
错误原因 :  Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
错误原因 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
错误原因 :  st.executeUpdate(sql_load): null]
[Line: 6]
[Near : {... runTystDMModel(_guid) ...}
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:458)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:204)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:215)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	... 25 more
由此错误引起 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : runTystDMModel( ... )' (Line:32). 
错误原因 :  Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
错误原因 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
错误原因 :  st.executeUpdate(sql_load): null
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:187)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:88)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:91)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.Function.call(Function.java:181)
	at com.leavay.dfc.mgr.env.FunctionWrapper.call(FunctionWrapper.java:191)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getMethod(ReflectiveAccessorOptimizer.java:932)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:385)
	... 28 more
由此错误引起 :  [Error: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
错误原因 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
错误原因 :  st.executeUpdate(sql_load): null]
[Line: 32]
[Near : {... insertDMData2Gbase8611(_guid) ...}
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:458)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:204)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:215)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	... 39 more
由此错误引起 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:50). 
错误原因 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
错误原因 :  st.executeUpdate(sql_load): null
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:187)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.Function.call(Function.java:181)
	at com.leavay.dfc.mgr.env.FunctionWrapper.call(FunctionWrapper.java:191)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getMethod(ReflectiveAccessorOptimizer.java:932)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:385)
	... 42 more
由此错误引起 :  java.lang.RuntimeException: org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
错误原因 :  st.executeUpdate(sql_load): null
	at org.mvel2.ast.TryNode.getReducedValueAccelerated(TryNode.java:158)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	... 48 more
由此错误引起 :  org.mvel2.ASTExecuteException: Error occurs at 'Glocal Function : insertDMData2Gbase8611( ... )' (Line:86). 
错误原因 :  st.executeUpdate(sql_load): null
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:187)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.TryNode.getReducedValueAccelerated(TryNode.java:139)
	... 49 more
由此错误引起 :  [Error: st.executeUpdate(sql_load): null]
[Line: 86]
[Near : {... result ...}
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:443)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:204)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:215)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.TypedVarNode.getReducedValueAccelerated(TypedVarNode.java:85)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:180)
	... 52 more
由此错误引起 :  java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor362.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getMethod(ReflectiveAccessorOptimizer.java:1013)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:385)
	... 59 more
由此错误引起 :  java.sql.SQLException: (GBA-01EX-700) Gbase general error: Task 681372 failed, [192.168.157.149:5050](GBA-02AD-0005)Failed to query in gnode:
DETAIL: (GBA-01-600) Gbase internal error: Task 681372, Too many bad records!
SQL: LOAD /*+ TID('104925321') */ DATA INFILE 'sftp://idf:Ies9sai|@192.168.157.153//export/idf/data/all/FFK/CCS/TJDS/R_SINGLECARBOAT.txt#offset=0&length=343910733&firstblock&ffsize=1375642931' INTO TABLE `ods_ffk_ccs_tjds`.`r_singlecarboat` DATA_FORMAT 3 FIELDS TERMINATED BY '' TABLE_FIELDS 'RSCB_ID,RCB_TYPE,RT
	at com.gbase.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.gbase.jdbc.GBaseIO.checkErrorPacket(GBaseIO.java:3603)
	at com.gbase.jdbc.GBaseIO.checkErrorPacket(GBaseIO.java:3535)
	at com.gbase.jdbc.GBaseIO.sendCommand(GBaseIO.java:1992)
	at com.gbase.jdbc.GBaseIO.sqlQueryDirect(GBaseIO.java:2146)
	at com.gbase.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2643)
	at com.gbase.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1680)
	at com.gbase.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1599)
	... 64 more
4.尝试过的解决方式：
找GBase的人帮我们分析得出有两种情况，第一是写入的列数和创建的列数对不上；第二是写入的列实际值超出了此数据类型设置的长度，或是列存入的值不是该类型的。

第一种情况：我们对了一下数据文件和建表语句里的列数是能对上的，可是我们查源端表结构和目标端表结构是对不上的；
第二种情况：我们发现生成数据文件时里面的数据没有分隔符，所以我们不明白怎么区分哪列对应哪列？生成时是怎么生成的？用数据文件导入数据时又是怎么区分的？

以下是对应的文件：
目标端表结构：gbase表结构.txt
源端表结构：oracle表结构.txt
源端查询的其中一条数据：R_SINGLECARBOAT表一条数据.xlsx
生成数据文件里对应的数据：数据文件里的第一条数据.txt

[R_SINGLECARBOAT表一条数据.xlsx](https://github.com/bugmeng/idfissues/files/2204301/R_SINGLECARBOAT.xlsx)
[数据文件里的第一条数据.txt](https://github.com/bugmeng/idfissues/files/2204302/default.txt)
[gbase表结构.txt](https://github.com/bugmeng/idfissues/files/2204303/gbase.txt)
[oracle表结构.txt](https://github.com/bugmeng/idfissues/files/2204304/oracle.txt)

**Comment by bugmeng** [comment]
问题：可是我们查源端表结构和目标端表结构是对不上的?
为什么表结构会对不上？？？？？没见过这样的问题
问题：我们发现生成数据文件时里面的数据没有分隔符
有没有分隔符，可以在执行shell中看，如果执行shell中有，结果没有那就是gbase的工具问题，还需要找gbase的人看。我看日志显示执行的shell中是有分隔符的。

**Comment by bugmeng** [comment]
如果你想快速处理，gbase人在的时候开视频会议拉上我们，不要轻易相信他们说不是他们的原因你就信了。要叫上我们，这样才能给你快速定位问题。

**Comment by weijianhuaaccp** [comment]
第一种情况，写入语句和建表语句能对上肯定不会报错，应该是别的原因
第二种情况，你们说分隔符用shell看，我在命令行里看不是一样的吗？我在命令行里看也是没有分隔符的

**Comment by bugmeng** [comment]
抽取日志你得发一下呀
